spring.application.name=swen2
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tourplanner}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tourplanner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tourplanner}
spring.jpa.hibernate.ddl-auto=update
app.jwt.secret=${APP_JWT_SECRET:zqj3chY8QWyDLzj6H9pwqfwpxdOTlq5v1FmG45RMYtvOWOF9Aq8Wccf2WuDToPuX}
app.jwt.expiration-minutes=${APP_JWT_EXPIRATION_MINUTES:60}
clients.ors.base-url=https://api.openrouteservice.org
clients.ors.api-key=${ORS_API_KEY:eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjQ2YmNlNTE1MGNlZjRjZTdhMmI2MTVjZGUxNzFmYjJiIiwiaCI6Im11cm11cjY0In0=}
clients.ors.connect-timeout-ms=2000
clients.ors.read-timeout-ms=5000