spring.application.name=swen2
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tourplanner}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tourplanner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tourplanner}
spring.jpa.hibernate.ddl-auto=create